networks:
  app-network:
    driver: bridge
services:
  backend:
    container_name: backend-go
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - app-network
    ports:
      - "15432:15432"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  backend-python:
    container_name: backend-py
    build:
      context: .
      dockerfile: backend-pdf/Dockerfile
    networks:
      - app-network
    ports:
      - "9000:9000"
    depends_on:
      - backend
      
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server_conf/clone_db.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c password_encryption=md5

volumes:
  db_data:
