services:
  backend:
    container_name: backend-go
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - app-network
    # ports:
    #   - "15432:15432"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # ports:
    #   - "5433:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server_conf/clone_db.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c password_encryption=md5

  frontend:
    build:
      context: ./vue-front
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - vue_dist:/app/dist

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - vue_dist:/usr/share/nginx/html

volumes:
  db_data:
  vue_dist:

networks:
  app-network:
    driver: bridge
