# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.11.8
FROM python:${PYTHON_VERSION}-slim as base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY . /app
WORKDIR /app/server_conf

# Создаем пользователя с домашним каталогом
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/home/appuser" \
    --shell "/bin/bash" \
    --uid "${UID}" \
    appuser \
    && chown -R appuser:appuser /home/appuser

# Устанавливаем зависимости
RUN apt-get update && apt-get install -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем Python-зависимости
RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=server_conf/requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt

ENV HOME=/home/appuser

# Переключаемся на пользователя
USER appuser

# Порт, используемый приложением
EXPOSE 5000

WORKDIR /app

# Запускаем приложение
CMD ["python", "./backend-pdf/app.py"]
